@ECHO OFF

SETLOCAL

CALL Vars.bat %1 || EXIT /B 

ECHO UE_HOME=%UE_HOME%
ECHO UE_VERSION=%UE_VERSION%

ECHO UE=%UE%

ECHO ROOT_DIR=%ROOT_DIR%

ECHO PROJECT=%PROJECT%
ECHO PROJECT_DIR=%PROJECT_DIR%
ECHO UPROJECT_PATH=%UPROJECT_PATH%

ECHO UE_EDITOR_EXE=%UE_EDITOR_EXE%
ECHO UE_EDITOR_CMD_EXE=%UE_EDITOR_CMD_EXE%
ECHO UE_BUILD_TOOL_BAT=%UE_BUILD_TOOL_BAT%

