@ECHO OFF

SETLOCAL

CALL Vars.bat %1 || EXIT /B 

ECHO Refreshing %UPROJECT_PATH%

SET CLEAN_CMD=Clean %PROJECT%
SET BUILD_CMD=Build %PROJECT%
SET OPEN_CMD=Open %PROJECT%

CALL %CLEAN_CMD% && %BUILD_CMD% && %OPEN_CMD%