@ECHO OFF

SETLOCAL

SET CURRENT_DIR=%~dp0

CALL "%CURRENT_DIR%Vars.bat" %1 || EXIT /B

ECHO Refreshing Project %PROJECT% at %UPROJECT_PATH%

SET CLEAN_CMD=Clean %PROJECT%
SET REGEN_CMD=Regen %PROJECT%
SET BUILD_CMD=Build %PROJECT%
SET OPEN_CMD=Open %PROJECT%

CALL %CLEAN_CMD% 
CALL %REGEN_CMD% 
CALL %BUILD_CMD% 
CALL %OPEN_CMD%